name: Copy to Private Repo

on:
  push:
    branches:
      - main

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "mooodali"
          git config --global user.email "modaliyari@gmail.com"

      - name: Push to Private Repo
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Set remote for the private repo with token in URL
          git remote add private https://github.com/your-username/NextChat-Private.git


          # Push the code to private repository
          git push private main
